# Generated by Django 4.0 on 2021-12-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('thumbnail', models.TextField(default='')),
                ('pub_date', models.DateTimeField()),
                ('yt_id', models.TextField(default='')),
            ],
        ),
    ]
